version: '3.3'

services:
  psql:
    container_name: room-psql
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./schema/data:/var/lib/postgresql/data
  
  app:
    container_name: room-app
    build:
      context: .
      dockerfile: Dockerfile
      image: room-app
    ports:
      - "8888:8888"
    depends_on:
      - psql
