version: '3.3'

services:
  database:
    container_name: room-sql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: room
      MYSQL_USER: thopb
      MYSQL_PASSWORD: 524020
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - room-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  backend:
    container_name: room-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - room-network

networks:
  room-network:
    driver: bridge
