// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/contract/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Create contract
				Method:  http.MethodPost,
				Path:    "/contract",
				Handler: CreateContractHandler(serverCtx),
			},
			{
				// Get contract
				Method:  http.MethodGet,
				Path:    "/contract/:id",
				Handler: GetContractHandler(serverCtx),
			},
			{
				// Delete contract
				Method:  http.MethodDelete,
				Path:    "/contract/:id",
				Handler: DeleteContractHandler(serverCtx),
			},
			{
				// Update contract
				Method:  http.MethodPut,
				Path:    "/contract/id",
				Handler: UpdateContractHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)
}
