// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/inventory/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFileHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/house",
					Handler: CreateHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/house/filter",
					Handler: FilterHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/house/:id",
					Handler: GetHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/house/:id/status",
					Handler: UpdateHouseStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/house/:id",
					Handler: UpdateHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/house/:id",
					Handler: DeleteHouseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/room",
					Handler: CreateRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/room/:id",
					Handler: UpdateRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/room/:id",
					Handler: DeleteRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/room/:id",
					Handler: GetRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/room/house/:id",
					Handler: GetRoomByHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/room/filter",
					Handler: FilterRoomHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/service",
					Handler: CreateServiceHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/service/:id",
					Handler: UpdateServiceHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/service/:id",
					Handler: DeleteServiceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/service/:id",
					Handler: GetServiceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/service/house/:id",
					Handler: GetServiceByHouseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)
}
