// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/inventory/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// FilterRoomGroup
				Method:  http.MethodGet,
				Path:    "/filter",
				Handler: FilterRoomGroupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/rooms"),
	)
}
