// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/inventory/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					// Create house
					Method:  http.MethodPost,
					Path:    "/house",
					Handler: CreateHouseHandler(serverCtx),
				},
				{
					// Get House
					Method:  http.MethodGet,
					Path:    "/house/:id",
					Handler: GetHouseHandler(serverCtx),
				},
				{
					// Update House
					Method:  http.MethodPut,
					Path:    "/house/:id",
					Handler: UpdateHouseHandler(serverCtx),
				},
				{
					// Delete House
					Method:  http.MethodDelete,
					Path:    "/house/:id",
					Handler: DeleteHouseHandler(serverCtx),
				},
				{
					// Update House Status
					Method:  http.MethodPut,
					Path:    "/house/:id/status",
					Handler: UpdateHouseStatusHandler(serverCtx),
				},
				{
					// Filter house
					Method:  http.MethodGet,
					Path:    "/house/filter",
					Handler: FilterHouseHandler(serverCtx),
				},
				{
					// Create room
					Method:  http.MethodPost,
					Path:    "/room",
					Handler: CreateRoomHandler(serverCtx),
				},
				{
					// Create Service
					Method:  http.MethodPost,
					Path:    "/service",
					Handler: CreateServiceHandler(serverCtx),
				},
				{
					// Upload file house
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFileHouseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)
}
