// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	classAlbumsFieldNames          = builder.RawFieldNames(&ClassAlbums{})
	classAlbumsRows                = strings.Join(classAlbumsFieldNames, ",")
	classAlbumsRowsExpectAutoSet   = strings.Join(stringx.Remove(classAlbumsFieldNames), ",")
	classAlbumsRowsWithPlaceHolder = strings.Join(stringx.Remove(classAlbumsFieldNames, "`id`"), "=?,") + "=?"
)

type (
	classAlbumsModel interface {
		Insert(ctx context.Context, data *ClassAlbums) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ClassAlbums, error)
		Update(ctx context.Context, data *ClassAlbums) error
		Delete(ctx context.Context, id int64) error
	}

	defaultClassAlbumsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ClassAlbums struct {
		Id        int64         `db:"id"`
		ClassId   sql.NullInt64 `db:"class_id"`
		Url       string        `db:"url"`
		Type      int64         `db:"type"`
		CreatedAt int64         `db:"created_at"`
		UpdatedAt int64         `db:"updated_at"`
		CreatedBy int64         `db:"created_by"`
		UpdatedBy int64         `db:"updated_by"`
	}
)

func newClassAlbumsModel(conn sqlx.SqlConn) *defaultClassAlbumsModel {
	return &defaultClassAlbumsModel{
		conn:  conn,
		table: "`class_albums`",
	}
}

func (m *defaultClassAlbumsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClassAlbumsModel) FindOne(ctx context.Context, id int64) (*ClassAlbums, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", classAlbumsRows, m.table)
	var resp ClassAlbums
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClassAlbumsModel) Insert(ctx context.Context, data *ClassAlbums) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, classAlbumsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ClassId, data.Url, data.Type, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultClassAlbumsModel) Update(ctx context.Context, data *ClassAlbums) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, classAlbumsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClassId, data.Url, data.Type, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultClassAlbumsModel) tableName() string {
	return m.table
}
