// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roomsFieldNames          = builder.RawFieldNames(&Rooms{})
	roomsRows                = strings.Join(roomsFieldNames, ",")
	roomsRowsExpectAutoSet   = strings.Join(stringx.Remove(roomsFieldNames), ",")
	roomsRowsWithPlaceHolder = strings.Join(stringx.Remove(roomsFieldNames, "`id`"), "=?,") + "=?"
)

type (
	roomsModel interface {
		Insert(ctx context.Context, data *Rooms) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Rooms, error)
		Update(ctx context.Context, data *Rooms) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoomsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Rooms struct {
		Id        int64         `db:"id"`
		ClassId   sql.NullInt64 `db:"class_id"`
		Name      string        `db:"name"`
		Status    int64         `db:"status"`
		CreatedAt int64         `db:"created_at"`
		UpdatedAt int64         `db:"updated_at"`
		CreatedBy int64         `db:"created_by"`
		UpdatedBy int64         `db:"updated_by"`
	}
)

func newRoomsModel(conn sqlx.SqlConn) *defaultRoomsModel {
	return &defaultRoomsModel{
		conn:  conn,
		table: "`rooms`",
	}
}

func (m *defaultRoomsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoomsModel) FindOne(ctx context.Context, id int64) (*Rooms, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roomsRows, m.table)
	var resp Rooms
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) Insert(ctx context.Context, data *Rooms) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, roomsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ClassId, data.Name, data.Status, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultRoomsModel) Update(ctx context.Context, data *Rooms) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roomsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClassId, data.Name, data.Status, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultRoomsModel) tableName() string {
	return m.table
}
