// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roomClassTblFieldNames          = builder.RawFieldNames(&RoomClassTbl{}, true)
	roomClassTblRows                = strings.Join(roomClassTblFieldNames, ",")
	roomClassTblRowsExpectAutoSet   = strings.Join(stringx.Remove(roomClassTblFieldNames), ",")
	roomClassTblRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(roomClassTblFieldNames, "id"))
)

type (
	roomClassTblModel interface {
		Insert(ctx context.Context, data *RoomClassTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RoomClassTbl, error)
		Update(ctx context.Context, data *RoomClassTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoomClassTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RoomClassTbl struct {
		Id        int64          `db:"id"`
		OwnerId   int64          `db:"owner_id"`
		HomeId    int64          `db:"home_id"`
		Name      string         `db:"name"`
		UnitPrice float64        `db:"unit_price"`
		Acreage   float64        `db:"acreage"`
		RoomInfo  sql.NullString `db:"room_info"`
		Type      int64          `db:"type"`   // 1: Apartment, 2: House, 4: Villa
		Status    int64          `db:"status"` // 1: Draft, 2: Active, 4: Inactive
		CreatedAt sql.NullInt64  `db:"created_at"`
		CreatedBy sql.NullInt64  `db:"created_by"`
		UpdatedAt sql.NullInt64  `db:"updated_at"`
		UpdatedBy sql.NullInt64  `db:"updated_by"`
	}
)

func newRoomClassTblModel(conn sqlx.SqlConn) *defaultRoomClassTblModel {
	return &defaultRoomClassTblModel{
		conn:  conn,
		table: `"public"."room_class_tbl"`,
	}
}

func (m *defaultRoomClassTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoomClassTblModel) FindOne(ctx context.Context, id int64) (*RoomClassTbl, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", roomClassTblRows, m.table)
	var resp RoomClassTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoomClassTblModel) Insert(ctx context.Context, data *RoomClassTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)", m.table, roomClassTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.OwnerId, data.HomeId, data.Name, data.UnitPrice, data.Acreage, data.RoomInfo, data.Type, data.Status, data.CreatedAt, data.CreatedBy, data.UpdatedAt, data.UpdatedBy)
	return ret, err
}

func (m *defaultRoomClassTblModel) Update(ctx context.Context, data *RoomClassTbl) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, roomClassTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.OwnerId, data.HomeId, data.Name, data.UnitPrice, data.Acreage, data.RoomInfo, data.Type, data.Status, data.CreatedAt, data.CreatedBy, data.UpdatedAt, data.UpdatedBy)
	return err
}

func (m *defaultRoomClassTblModel) tableName() string {
	return m.table
}
