// Code generated by goctl. DO NOT EDIT.
package types

type CreateContractReq struct {
	RoomID         int64  `form:"roomID"`
	Description    string `form:"description"`
	ContractUrl    string `form:"contractUrl"`
	Start          int64  `form:"start"`
	End            int64  `form:"end"`
	ContractRenter string `form:"contractRenter"`
	ContractDetail string `form:"contractDetail"`
	Type           int64  `form:"type"`
	Deposit        int64  `form:"deposit"`
	Deadline       int64  `form:"deadline"`
	DepositUrl     string `form:"depositUrl"`
}

type CreateContractRes struct {
	Result   Result   `json:"result"`
	Contract Contract `json:"contract"`
}

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type User struct {
	UserID    int64  `json:"userID"`
	Phone     string `json:"phone"`
	FullName  string `json:"fullName"`
	Birthday  int64  `json:"birthday"`
	AvatarUrl string `json:"avatarUrl"`
	Address   string `json:"address"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type House struct {
	HouseID     int64     `json:"houseID"`
	UserID      int64     `json:"userID"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        int64     `json:"type"`
	Area        int64     `json:"area"`
	Price       int64     `json:"price"`
	Status      int64     `json:"status"`
	Address     string    `json:"address"`
	WardID      int64     `json:"wardID"`
	DistrictID  int64     `json:"districtID"`
	ProvinceID  int64     `json:"provinceID"`
	CreatedAt   int64     `json:"createdAt"`
	UpdatedAt   int64     `json:"updatedAt"`
	CreatedBy   int64     `json:"createdBy"`
	UpdatedBy   int64     `json:"updatedBy"`
	Albums      []Album   `json:"albums"`
	Rooms       []Room    `json:"rooms"`
	Services    []Service `json:"services"`
}

type Album struct {
	AlbumID   int64  `json:"albumID"`
	HouseID   int64  `json:"houseID"`
	Url       string `json:"url"`
	Type      int64  `json:"type"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	CreatedBy int64  `json:"createdBy"`
	UpdatedBy int64  `json:"updatedBy"`
}

type Room struct {
	RoomID    int64  `json:"roomID"`
	HouseID   int64  `json:"houseID"`
	Name      string `json:"name"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	CreatedBy int64  `json:"createdBy"`
	UpdatedBy int64  `json:"updatedBy"`
}

type Service struct {
	ServiceID int64  `json:"serviceID"`
	HouseID   int64  `json:"houseID"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Type      int64  `json:"type"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	CreatedBy int64  `json:"createdBy"`
	UpdatedBy int64  `json:"updatedBy"`
}

type Contract struct {
	ContractID      int64            `json:"contractID"`
	RoomID          int64            `json:"roomID"`
	Description     string           `json:"description"`
	ContractUrl     string           `json:"contractUrl"`
	Start           int64            `json:"start"`
	End             int64            `json:"end"`
	Status          int64            `json:"status"`
	Type            int64            `json:"type"`
	Deposit         int64            `json:"deposit"`
	Deadline        int64            `json:"deadline"`
	CreatedAt       int64            `json:"createdAt"`
	UpdatedAt       int64            `json:"updatedAt"`
	CreatedBy       int64            `json:"createdBy"`
	UpdatedBy       int64            `json:"updatedBy"`
	ContractRenters []ContractRenter `json:"contractRenters"`
	ContractDetails []ContractDetail `json:"contractDetails"`
}

type ContractRenter struct {
	ID         int64 `json:"id"`
	ContractID int64 `json:"contractID"`
	RenterID   int64 `json:"renterID"`
	Type       int64 `json:"type"`
	Status     int64 `json:"status"`
}

type ContractDetail struct {
	ID         int64 `json:"id"`
	ContractID int64 `json:"contractID"`
	ServiceID  int64 `json:"serviceID"`
	Price      int64 `json:"price"`
	Index      int64 `json:"index"`
	Type       int64 `json:"type"`
}

type Payment struct {
	ID         int64 `json:"id"`
	ContractID int64 `json:"contractID"`
	Month      int64 `json:"month"`
	Total      int64 `json:"total"`
	Status     int64 `json:"status"`
	CreatedAt  int64 `json:"createdAt"`
	UpdatedAt  int64 `json:"updatedAt"`
	CreatedBy  int64 `json:"createdBy"`
	UpdatedBy  int64 `json:"updatedBy"`
}

type PaymentUsed struct {
	ID        int64 `json:"id"`
	PaymentID int64 `json:"paymentID"`
	ServiceID int64 `json:"serviceID"`
	Index     int64 `json:"index"`
	Status    int64 `json:"status"`
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt int64 `json:"updatedAt"`
	CreatedBy int64 `json:"createdBy"`
	UpdatedBy int64 `json:"updatedBy"`
}

type PaymentDetail struct {
	ID        int64  `json:"id"`
	PaymentID int64  `json:"paymentID"`
	Amount    int64  `json:"amount"`
	Type      int64  `json:"type"`
	Utl       string `json:"utl"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	CreatedBy int64  `json:"createdBy"`
	UpdatedBy int64  `json:"updatedBy"`
}
