// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/payment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					// Momo payment
					Method:  http.MethodPost,
					Path:    "/momo",
					Handler: MomoPaymentHandler(serverCtx),
				},
				{
					// Momo webhook
					Method:  http.MethodPost,
					Path:    "/momo/webhook",
					Handler: MomoWebhookHandler(serverCtx),
				},
				{
					// Upload file house
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFilePaymentHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/payment"),
	)
}
