// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"user_name"` // user_name
	Password string `json:"password"`  //  password
}

type LoginRes struct {
	Result Result `json:"result"`
	Token  string `json:"token"` // jwt token for api
	User   User   `json:"user"`  // Account info
}

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type User struct {
}
