// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentFieldNames          = builder.RawFieldNames(&Payment{})
	paymentRows                = strings.Join(paymentFieldNames, ",")
	paymentRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentFieldNames), ",")
	paymentRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentFieldNames, "`id`"), "=?,") + "=?"
)

type (
	paymentModel interface {
		Insert(ctx context.Context, data *Payment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Payment, error)
		Update(ctx context.Context, data *Payment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Payment struct {
		Id        int64  `db:"id"`
		BillId    int64  `db:"bill_id"`
		Amount    int64  `db:"amount"`
		Type      int64  `db:"type"`
		Url       string `db:"url"`
		CreatedAt int64  `db:"created_at"`
		UpdatedAt int64  `db:"updated_at"`
		CreatedBy int64  `db:"created_by"`
		UpdatedBy int64  `db:"updated_by"`
	}
)

func newPaymentModel(conn sqlx.SqlConn) *defaultPaymentModel {
	return &defaultPaymentModel{
		conn:  conn,
		table: "`payment`",
	}
}

func (m *defaultPaymentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentModel) FindOne(ctx context.Context, id int64) (*Payment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentRows, m.table)
	var resp Payment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentModel) Insert(ctx context.Context, data *Payment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, paymentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BillId, data.Amount, data.Type, data.Url, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultPaymentModel) Update(ctx context.Context, data *Payment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BillId, data.Amount, data.Type, data.Url, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultPaymentModel) tableName() string {
	return m.table
}
