// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentTblFieldNames          = builder.RawFieldNames(&PaymentTbl{})
	paymentTblRows                = strings.Join(paymentTblFieldNames, ",")
	paymentTblRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentTblFieldNames), ",")
	paymentTblRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	paymentTblModel interface {
		Insert(ctx context.Context, data *PaymentTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PaymentTbl, error)
		Update(ctx context.Context, data *PaymentTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PaymentTbl struct {
		Id         int64 `db:"id"`
		ContractId int64 `db:"contract_id"`
		Month      int64 `db:"month"`
		Total      int64 `db:"total"`
		Status     int64 `db:"status"`
		CreatedAt  int64 `db:"created_at"`
		UpdatedAt  int64 `db:"updated_at"`
		CreatedBy  int64 `db:"created_by"`
		UpdatedBy  int64 `db:"updated_by"`
	}
)

func newPaymentTblModel(conn sqlx.SqlConn) *defaultPaymentTblModel {
	return &defaultPaymentTblModel{
		conn:  conn,
		table: "`payment_tbl`",
	}
}

func (m *defaultPaymentTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentTblModel) FindOne(ctx context.Context, id int64) (*PaymentTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentTblRows, m.table)
	var resp PaymentTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentTblModel) Insert(ctx context.Context, data *PaymentTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, paymentTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ContractId, data.Month, data.Total, data.Status, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultPaymentTblModel) Update(ctx context.Context, data *PaymentTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ContractId, data.Month, data.Total, data.Status, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultPaymentTblModel) tableName() string {
	return m.table
}
