// Code generated by goctl. DO NOT EDIT.
package types

type CreateHomeReq struct {
	Name         string `form:"name"`
	Description  string `form:"description"`
	ProvinceCode int64  `form:"province_code"`
	DistrictCode int64  `form:"district_code"`
	WardCode     int64  `form:"ward_code"`
	Address      string `form:"address"`
	Wifi         int64  `form:"wifi"`
	Electricity  int64  `form:"electricity"`
	Water        int64  `form:"water"`
	Cleaning     int64  `form:"cleaning"`
	Parking      int64  `form:"parking"`
	Security     int64  `form:"security"`
	Other        string `form:"other"`
}

type CreateHomeRes struct {
	Result Result `json:"result"`
	Home   Home   `json:"home"`
}

type DeleteHomeReq struct {
	ID int64 `path:"id"`
}

type DeleteHomeRes struct {
	Result Result `json:"result"`
}

type FilterHomeReq struct {
}

type FilterHomeRes struct {
	Result Result `json:"result"`
	Homes  []Home `json:"homes"`
}

type FilterRoomClassReq struct {
	ProvinceCode int   `form:"province_code"`
	DistrictCode int   `form:"district_code"`
	WardCode     int   `form:"ward_code"`
	PriceFrom    int64 `form:"price_from"`
	PriceTo      int64 `form:"price_to"`
	AcreageFrom  int64 `form:"acreage_from"`
	AcreageTo    int64 `form:"acreage_to"`
}

type FilterRoomClassRes struct {
	Result      Result      `json:"result"`
	RoomClasses []RoomClass `json:"roomClasses"`
}

type GetHomeReq struct {
	ID int64 `path:"id"`
}

type GetHomeRes struct {
	Result Result `json:"result"`
	Home   Home   `json:"home"`
}

type Home struct {
	HomeID      int64  `json:"homeID"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Province    string `json:"province"`
	District    string `json:"district"`
	Ward        string `json:"ward"`
	Address     string `json:"address"`
	Wifi        int64  `json:"wifi"`
	Electricity int64  `json:"electricity"`
	Water       int64  `json:"water"`
	Cleaning    int64  `json:"cleaning"`
	Parking     int64  `json:"parking"`
	Security    int64  `json:"security"`
	Other       string `json:"other"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	CreatedBy   int64  `json:"createdBy"`
	UpdatedBy   int64  `json:"updatedBy"`
}

type Profile struct {
	ProfileID int64  `json:"profileID"`
	FullName  string `json:"fullName"`
	Dob       int64  `json:"dob"`
	AvatarUrl string `json:"avatarUrl"`
	Address   string `json:"address"`
	Phone     string `json:"phone"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	CreatedBy int64  `json:"createdBy"`
	UpdatedBy int64  `json:"updatedBy"`
}

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type RoomClass struct {
	RoomClassID int64  `json:"roomClassID"`
	Province    string `json:"province"`
	District    string `json:"district"`
	Ward        string `json:"ward"`
	Price       int64  `json:"price"`
	Acreage     int64  `json:"acreage"`
	TotalRoom   int64  `json:"totalRoom"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	CreatedBy   int64  `json:"createdBy"`
	UpdatedBy   int64  `json:"updatedBy"`
}

type UpdateHomeReq struct {
	Name         string `form:"name"`
	Description  string `form:"description"`
	ProvinceCode int64  `form:"province_code"`
	DistrictCode int64  `form:"district_code"`
	WardCode     int64  `form:"ward_code"`
	Address      string `form:"address"`
	Wifi         int64  `form:"wifi"`
	Electricity  int64  `form:"electricity"`
	Water        int64  `form:"water"`
	Cleaning     int64  `form:"cleaning"`
	Parking      int64  `form:"parking"`
	Security     int64  `form:"security"`
	Other        string `form:"other"`
	Status       int64  `form:"status"`
}

type UpdateHomeRes struct {
	Result Result `json:"result"`
	Home   Home   `json:"home"`
}

type User struct {
	UserID    int64  `json:"userID"`
	ProfileID int64  `json:"profileID"`
	UserName  string `json:"userName"`
	Email     string `json:"email"`
}
