// Code generated by goctl. DO NOT EDIT.
package types

type Album struct {
	AlbumID int64  `json:"albumID"`
	HouseID int64  `json:"houseID"`
	Url     string `json:"url"`
}

type Bill struct {
	BillID      int64        `json:"billID"`
	PaymentID   int64        `json:"paymentID"`
	PaymentDate int64        `json:"paymentDate"`
	Amount      int64        `json:"amount"`
	Status      int64        `json:"status"`
	BillDetails []BillDetail `json:"billDetails"`
}

type BillDetail struct {
	BillDetailID int64  `json:"billDetailID"`
	BillID       int64  `json:"billID"`
	Name         int64  `json:"name"`
	Price        int64  `json:"price"`
	Type         string `json:"type"`
	Quantity     int64  `json:"quantity"`
}

type BillPay struct {
	BillPayID int64 `json:"billPayID"`
	BillID    int64 `json:"billID"`
	Amount    int64 `json:"amount"`
	PayDate   int64 `json:"payDate"`
	UserID    int64 `json:"userID"`
}

type Contract struct {
	ContractID      int64            `json:"contractID"`
	Code            string           `json:"code"`
	Status          int64            `json:"status"`
	RenterID        int64            `json:"renterID"`
	RenterNumber    string           `json:"renterNumber"`
	RenterDate      int64            `json:"renterDate"`
	RenterAddress   string           `json:"renterAddress"`
	RenterName      string           `json:"renterName"`
	LessorID        int64            `json:"lessorID"`
	LessorNumber    string           `json:"lessorNumber"`
	LessorDate      int64            `json:"lessorDate"`
	LessorAddress   string           `json:"lessorAddress"`
	LessorName      string           `json:"lessorName"`
	RoomID          int64            `json:"roomID"`
	CheckIn         int64            `json:"checkIn"`
	Duration        int64            `json:"duration"`
	Purpose         string           `json:"purpose"`
	ContractRenters []ContractRenter `json:"contractRenters"`
	ContractDetails []ContractDetail `json:"contractDetails"`
	Payment         struct {
		PaymentID   int64 `json:"paymentID"`
		ContractID  int64 `json:"contractID"`
		Amount      int64 `json:"amount"`
		Discount    int64 `json:"discount"`
		Deposit     int64 `json:"deposit"`
		DepositDate int64 `json:"depositDate"`
		NextBill    int64 `json:"nextBill"`
	} `json:"payment"`
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt int64 `json:"updatedAt"`
	CreatedBy int64 `json:"createdBy"`
	UpdatedBy int64 `json:"updatedBy"`
}

type ContractDetail struct {
	ID         int64  `json:"id"`
	ContractID int64  `json:"contractID"`
	Name       string `json:"name"`
	Price      int64  `json:"price"`
	Type       int64  `json:"type"`
}

type ContractRenter struct {
	ID         int64 `json:"id"`
	ContractID int64 `json:"contractID"`
	RenterID   int64 `json:"renterID"`
}

type CreateHouseReq struct {
	Name        string `form:"name"`
	Description string `form:"description"`
	Type        int64  `form:"type"`
	Area        int64  `form:"area"`
	Price       int64  `form:"price"`
	BedNum      int    `form:"bedNum,optional"`
	LivingNum   int    `form:"livingNum,optional"`
	Address     string `form:"address"`
	WardID      int64  `form:"wardID"`
	DistrictID  int64  `form:"districtID"`
	ProvinceID  int64  `form:"provinceID"`
	Albums      string `form:"albums,optional"`
}

type CreateHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	House struct {
		HouseID     int64     `json:"houseID"`
		UserID      int64     `json:"userID"`
		Name        string    `json:"name"`
		Description string    `json:"description"`
		Type        int64     `json:"type"`
		Status      int64     `json:"status"`
		Area        int64     `json:"area"`
		Price       int64     `json:"price"`
		BedNum      int64     `json:"bedNum"`
		LivingNum   int64     `json:"livingNum"`
		Albums      []string  `json:"albums"`
		Rooms       []Room    `json:"rooms"`
		Services    []Service `json:"services"`
		Address     string    `json:"address"`
		WardID      int64     `json:"wardID"`
		DistrictID  int64     `json:"districtID"`
		ProvinceID  int64     `json:"provinceID"`
		CreatedAt   int64     `json:"createdAt"`
		UpdatedAt   int64     `json:"updatedAt"`
		CreatedBy   int64     `json:"createdBy"`
		UpdatedBy   int64     `json:"updatedBy"`
	} `json:"house"`
}

type CreateRoomReq struct {
	HouseID  int64  `form:"houseID"`
	Name     string `form:"name"`
	Capacity int64  `form:"capacity"`
}

type CreateRoomRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Room struct {
		RoomID   int64  `json:"roomID"`
		HouseID  int64  `json:"houseID"`
		Name     string `json:"name"`
		Status   int64  `json:"status"`
		Capacity int64  `json:"capacity"`
		EIndex   int64  `json:"eIndex"`
		WIndex   int64  `json:"wIndex"`
	} `json:"room"`
}

type CreateServiceReq struct {
	HouseID int64  `form:"houseID"`
	Name    string `form:"name"`
	Price   int64  `form:"price"`
	Unit    int64  `form:"unit"`
}

type CreateServiceRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Service struct {
		ServiceID int64  `json:"serviceID"`
		HouseID   int64  `json:"houseID"`
		Name      string `json:"name"`
		Price     int64  `json:"price"`
		Unit      int64  `json:"unit"`
	} `json:"service"`
}

type DeleteHouseReq struct {
	HouseID int64 `path:"id"`
}

type DeleteHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
}

type DeleteRoomReq struct {
	RoomID int64 `path:"id"`
}

type DeleteRoomRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
}

type DeleteServiceReq struct {
	ServiceID int64 `path:"id"`
}

type DeleteServiceRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
}

type FilterHouseReq struct {
	Search string `form:"search,optional"`
	Limit  int64  `form:"limit"`
	Offset int64  `form:"offset"`
}

type FilterHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Total      int64   `json:"total"`
	ListHouses []House `json:"listHouses"`
}

type GetHouseReq struct {
	ID int64 `path:"id"`
}

type GetHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	House struct {
		HouseID     int64     `json:"houseID"`
		UserID      int64     `json:"userID"`
		Name        string    `json:"name"`
		Description string    `json:"description"`
		Type        int64     `json:"type"`
		Status      int64     `json:"status"`
		Area        int64     `json:"area"`
		Price       int64     `json:"price"`
		BedNum      int64     `json:"bedNum"`
		LivingNum   int64     `json:"livingNum"`
		Albums      []string  `json:"albums"`
		Rooms       []Room    `json:"rooms"`
		Services    []Service `json:"services"`
		Address     string    `json:"address"`
		WardID      int64     `json:"wardID"`
		DistrictID  int64     `json:"districtID"`
		ProvinceID  int64     `json:"provinceID"`
		CreatedAt   int64     `json:"createdAt"`
		UpdatedAt   int64     `json:"updatedAt"`
		CreatedBy   int64     `json:"createdBy"`
		UpdatedBy   int64     `json:"updatedBy"`
	} `json:"house"`
}

type GetRoomByHouseReq struct {
	HouseID int64 `path:"id"`
	Limit   int64 `form:"limit"`
	Offset  int64 `form:"offset"`
}

type GetRoomByHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Total int    `json:"total"`
	Rooms []Room `json:"rooms"`
}

type GetRoomReq struct {
	RoomID int64 `path:"id"`
}

type GetRoomRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Room struct {
		RoomID   int64  `json:"roomID"`
		HouseID  int64  `json:"houseID"`
		Name     string `json:"name"`
		Status   int64  `json:"status"`
		Capacity int64  `json:"capacity"`
		EIndex   int64  `json:"eIndex"`
		WIndex   int64  `json:"wIndex"`
	} `json:"room"`
}

type GetServiceByHouseReq struct {
	HouseID int64 `path:"id"`
}

type GetServiceByHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Services []Service `json:"services"`
}

type GetServiceReq struct {
	ServiceID int64 `path:"id"`
}

type GetServiceRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Service struct {
		ServiceID int64  `json:"serviceID"`
		HouseID   int64  `json:"houseID"`
		Name      string `json:"name"`
		Price     int64  `json:"price"`
		Unit      int64  `json:"unit"`
	} `json:"service"`
}

type House struct {
	HouseID     int64     `json:"houseID"`
	UserID      int64     `json:"userID"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        int64     `json:"type"`
	Status      int64     `json:"status"`
	Area        int64     `json:"area"`
	Price       int64     `json:"price"`
	BedNum      int64     `json:"bedNum"`
	LivingNum   int64     `json:"livingNum"`
	Albums      []string  `json:"albums"`
	Rooms       []Room    `json:"rooms"`
	Services    []Service `json:"services"`
	Address     string    `json:"address"`
	WardID      int64     `json:"wardID"`
	DistrictID  int64     `json:"districtID"`
	ProvinceID  int64     `json:"provinceID"`
	CreatedAt   int64     `json:"createdAt"`
	UpdatedAt   int64     `json:"updatedAt"`
	CreatedBy   int64     `json:"createdBy"`
	UpdatedBy   int64     `json:"updatedBy"`
}

type Payment struct {
	PaymentID   int64 `json:"paymentID"`
	ContractID  int64 `json:"contractID"`
	Amount      int64 `json:"amount"`
	Discount    int64 `json:"discount"`
	Deposit     int64 `json:"deposit"`
	DepositDate int64 `json:"depositDate"`
	NextBill    int64 `json:"nextBill"`
}

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type Room struct {
	RoomID   int64  `json:"roomID"`
	HouseID  int64  `json:"houseID"`
	Name     string `json:"name"`
	Status   int64  `json:"status"`
	Capacity int64  `json:"capacity"`
	EIndex   int64  `json:"eIndex"`
	WIndex   int64  `json:"wIndex"`
}

type Service struct {
	ServiceID int64  `json:"serviceID"`
	HouseID   int64  `json:"houseID"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Unit      int64  `json:"unit"`
}

type UpdateHouseReq struct {
	HouseID     int64  `path:"id"`
	Name        string `form:"name"`
	Description string `form:"description"`
	Type        int64  `form:"type"`
	Util        int64  `form:"util,optional"`
	Area        int64  `form:"area"`
	Price       int64  `form:"price"`
	BedNum      int    `form:"bedNum,optional"`
	LivingNum   int    `form:"livingNum,optional"`
	Address     string `form:"address"`
	WardID      int64  `form:"wardID"`
	DistrictID  int64  `form:"districtID"`
	ProvinceID  int64  `form:"provinceID"`
	Albums      string `form:"albums"`
}

type UpdateHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	House struct {
		HouseID     int64     `json:"houseID"`
		UserID      int64     `json:"userID"`
		Name        string    `json:"name"`
		Description string    `json:"description"`
		Type        int64     `json:"type"`
		Status      int64     `json:"status"`
		Area        int64     `json:"area"`
		Price       int64     `json:"price"`
		BedNum      int64     `json:"bedNum"`
		LivingNum   int64     `json:"livingNum"`
		Albums      []string  `json:"albums"`
		Rooms       []Room    `json:"rooms"`
		Services    []Service `json:"services"`
		Address     string    `json:"address"`
		WardID      int64     `json:"wardID"`
		DistrictID  int64     `json:"districtID"`
		ProvinceID  int64     `json:"provinceID"`
		CreatedAt   int64     `json:"createdAt"`
		UpdatedAt   int64     `json:"updatedAt"`
		CreatedBy   int64     `json:"createdBy"`
		UpdatedBy   int64     `json:"updatedBy"`
	} `json:"house"`
}

type UpdateHouseStatusReq struct {
	HouseID int64 `path:"id"`
	Status  int64 `form:"status"`
}

type UpdateHouseStatusRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
}

type UpdateRoomReq struct {
	RoomID   int64  `path:"id"`
	Name     string `form:"name"`
	Capacity int64  `form:"capacity"`
}

type UpdateRoomRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Room struct {
		RoomID   int64  `json:"roomID"`
		HouseID  int64  `json:"houseID"`
		Name     string `json:"name"`
		Status   int64  `json:"status"`
		Capacity int64  `json:"capacity"`
		EIndex   int64  `json:"eIndex"`
		WIndex   int64  `json:"wIndex"`
	} `json:"room"`
}

type UpdateServiceReq struct {
	ServiceID int64  `path:"id"`
	Name      string `form:"name"`
	Price     int64  `form:"price"`
	Unit      int64  `form:"unit"`
}

type UpdateServiceRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Service struct {
		ServiceID int64  `json:"serviceID"`
		HouseID   int64  `json:"houseID"`
		Name      string `json:"name"`
		Price     int64  `json:"price"`
		Unit      int64  `json:"unit"`
	} `json:"service"`
}

type UploadFileHouseReq struct {
	HouseID int64 `form:"houseID,optional"`
}

type UploadFileHouseRes struct {
	Result struct {
		Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
		Message string `json:"message"` // Result message: detail response code
	} `json:"result"`
	Url string `json:"url"`
}

type User struct {
	UserID      int64  `json:"userID"`
	Phone       string `json:"phone"`
	Role        int64  `json:"role"`
	Status      int64  `json:"status"`
	Address     string `json:"address"`
	FullName    string `json:"fullName"`
	AvatarUrl   string `json:"avatarUrl"`
	Birthday    int64  `json:"birthday"`
	Gender      int64  `json:"gender"`
	CccdNumber  string `json:"cccdNumber"`
	CccdDate    int64  `json:"cccdDate"`
	CccdAddress string `json:"cccdAddress"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}
